version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongodb_datas_tmp:/data/db

volumes:
  mongodb_datas_tmp: