version: '3.7'

services:
  db:
     image: mariadb
     container_name: mariadb1
     ports:
          - 3308:3306
     restart: always
     volumes:
        - mariadb_datas:/var/lib/mysql
     environment:
        MARIADB_ROOT_PASSWORD: 1234

volumes:
    mariadb_datas: 